spring:
  config:
    import: optional:consul:${spring.cloud.consul.host}:${spring.cloud.consul.port}
  datasource:
    url: jdbc:mysql://localhost:3306/spring-learn?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  cloud:
    consul:
      host: localhost
      port: 8500

logstash:
  url: 114.116.240.82:5044
