server:
  port: 8088

spring:
  application:
    name: cms
  #数据源
  datasource:
    name: springboot
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #时间戳统一转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  freemarker:
    suffix: .html

minio:
  endpoint: http://114.116.240.82:9000
  access-key: minio
  secret-key: minio@123456

logstash:
  url: 114.116.240.82:5044
